return {
    PASS_THE_BOMB = "PassTheBomb",
    RISING_LAVA = "RisingLava",
    TACOS_OF_DEATH = "TacosOfDeath",
    TRAINS = "Trains",
    DODGE_SPIKES = "DodgeSpikes",
    SANS_LASERS = "SansLasers",
    GOOMBA_STOMP = "GoombaStomp",
    PARKOUR_TOWER = "ParkourTower",
    TEAM_GRAVEYARD = "TeamGraveyard",
    ["1x1x1x1 Sword"] = "1x1x1x1 Sword",
    TILE_OUTLINE = "TileOutline",
    FARTHEST_FROM_BALL_LOSES = "FarthestFromBallLoses",
    SWORD_FIGHT = "SwordFight",
    SLAP_BATTLE = "SlapBattle",
    MUSICAL_CHAIRS = "MusicalChairs",
    
    BLIND_SHOOTING = "BlindShooting",
    LASER_PARKOUR = "LaserParkour",
    JENGA_CANNON = "JengaCannon",
    CHOOSE_COLOR = "ChooseColor", -- OR DIE
    BALDIS_MATH_QUIZ = "BaldisMathQuiz",

    -- VAULTED
    CAT_AND_MOUSE = "CatAndMouse",
}
